let express=require("express")
const { login, adduser,sendotp,resetpwd,isLoggedIn,isAdmin } = require("../controlers/usercont")
let { addprod, getprods, getprodbyid, getprodbycat, searchprod, updateprodimg,upload, deleteprod,updateprod, addrev } = require("../controlers/prodcon")
let { addcart, getcartitems, inccartqty, deccartqty, deletecartitem } = require("../controlers/cartcon")
let rt=new express.Router()
rt.post("/login",login)
rt.post("/reg",adduser)
rt.post("/addprod",upload.single("img"),isAdmin,addprod)
rt.get("/getprods",getprods)
rt.get("/getprodbyid/:id",getprodbyid)
rt.get("/getprodbycat/:cat",getprodbycat)
rt.get("/searchprod/:title",searchprod)
rt.put("/updateprodimg",upload.single("img"),isAdmin,updateprodimg)
rt.put("/updateprod",isAdmin,updateprod)
rt.delete("/delprod/:id",isAdmin,deleteprod)
rt.post("/addcart",isLoggedIn,addcart)
rt.get("/getcartitems/:uid",isLoggedIn,getcartitems)
rt.get("/inccartqty/:cid",isLoggedIn,inccartqty)
rt.get("/deccartqty/:cid",isLoggedIn,deccartqty)
rt.delete("/deletecartitem/:cid",isLoggedIn,deletecartitem)
rt.post("/addrev",isLoggedIn,addrev)
rt.get("/sendotp/:eid",sendotp)
rt.post("/resetpwd",resetpwd)
module.exports=rt